# Generated by Django 2.2.4 on 2019-09-01 03:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The category's name", max_length=200)),
                ('description', models.TextField(blank=True, help_text='A brief description of the category', max_length=500)),
                ('hidden', models.BooleanField(default=False, help_text='Whether this category will be hidden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', related_query_name='expense_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'expense categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the expense', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of money spent', max_digits=12)),
                ('date', models.DateField(default=datetime.date.today, help_text='Date of the expense')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for this expense', max_length=500)),
                ('category', models.ForeignKey(help_text='Select an expense category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', related_query_name='expense', to='core.ExpenseCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', related_query_name='expense', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
